# Generated by Django 3.2.3 on 2021-05-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('boost', models.FloatField()),
                ('lvl', models.FloatField()),
                ('nextLvl', models.FloatField()),
            ],
        ),
    ]
