# Generated by Django 3.2.3 on 2021-06-12 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stGame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreinformation',
            name='nextLvl',
        ),
        migrations.AddField(
            model_name='scoreinformation',
            name='nextLvl_click',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='scoreinformation',
            name='nextLvl_hit',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='scoreinformation',
            name='score_hit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scoreinformation',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scoreinformation',
            name='boost',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scoreinformation',
            name='lvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scoreinformation',
            name='score',
            field=models.IntegerField(default=500),
        ),
    ]
